"use client";
import {FormEvent,useState} from "react";
type Video={id:string;platform:string;creator:string;title:string;description:string;duration:string;durationSeconds:number;publishedAt:string;age:string;score:number;thumbnail:string;url:string;classification?:{confidence:number;reasons:string[];type:string}};
type Source={id:string;name:string;status:string};
const platforms=["All","YouTube","TikTok","Reddit","Instagram","X","Facebook","Twitch","Dailymotion"];
const ids:Record<string,string>={All:"all",YouTube:"youtube",TikTok:"tiktok",Reddit:"reddit",Instagram:"instagram",X:"x",Facebook:"facebook",Twitch:"twitch",Dailymotion:"dailymotion"};
const suggestions=["funny cat moments","unexpected Roblox moments","crazy football skills","street magic","cute animals"];
export default function Home(){
 const [query,setQuery]=useState("");const [searched,setSearched]=useState(false);const [active,setActive]=useState("All");const [sort,setSort]=useState("relevance");const [duration,setDuration]=useState("any");const [loading,setLoading]=useState(false);const [results,setResults]=useState<Video[]>([]);const [live,setLive]=useState(false);const [demo,setDemo]=useState(true);const [error,setError]=useState("");const [filteredCount,setFilteredCount]=useState(0);const [duplicateCount,setDuplicateCount]=useState(0);const [sources,setSources]=useState<Source[]>([]);const [limit,setLimit]=useState(24);const [showDetails,setShowDetails]=useState(false);
 async function submit(e?:FormEvent){e?.preventDefault();await runSearch(query,limit);}
 async function runSearch(q=query,nextLimit=limit){const clean=q.trim();if(!clean)return;setLoading(true);setSearched(true);setError("");try{const res=await fetch(`/api/search?q=${encodeURIComponent(clean)}&platform=${ids[active]}&sort=${sort}&duration=${duration}&limit=${nextLimit}`);const data=await res.json();if(!res.ok)throw new Error(data.error||"Search request failed");setResults(data.results||[]);setLive(Boolean(data.live));setDemo(Boolean(data.demo));setFilteredCount(Number(data.filteredCount||0));setDuplicateCount(Number(data.duplicateCount||0));setSources(data.sources||[]);}catch(err){setResults([]);setError(err instanceof Error?err.message:"Search failed");}finally{setLoading(false)}}
 function choosePlatform(p:string){setActive(p);if(searched)window.setTimeout(()=>runSearch(query,limit),0)}
 function chooseSort(v:string){setSort(v);if(searched)window.setTimeout(()=>runSearch(query,limit),0)}
 function chooseDuration(v:string){setDuration(v);if(searched)window.setTimeout(()=>runSearch(query,limit),0)}
 function reset(){setQuery("");setSearched(false);setResults([]);setError("");setLimit(24)}
 return <main><nav className="nav"><button className="brand" onClick={reset}><span className="brandMark">▶</span><span>ClipScout</span><span className="beta">BETA</span></button><div className="navRight"><span className={live?"statusDot":"statusDot offline"}/>{live?"Live source connected":demo?"Demo / connector-ready":"Searching sources"}</div></nav>
 {!searched?<section className="hero"><div className="eyebrow">CROSS-PLATFORM VIDEO SEARCH</div><h1>Find the <span>video.</span><br/>Not the compilation.</h1><p className="subtitle">Search supported platforms for individual clips while pushing compilations, rankings, mashups and obvious duplicates out of the way.</p><Search value={query} setValue={setQuery} submit={submit}/><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>{setQuery(s);setSearched(true);setTimeout(()=>runSearch(s,24),0)}}>“{s}”</button>)}</div><div className="platformRow">{platforms.slice(1).map(p=><span key={p}>{p}</span>)}</div><div className="featureGrid"><Feature icon="◈" title="Multi-source" text="One search interface for up to 8 supported platforms."/><Feature icon="✦" title="Clip-first" text="Standalone videos are prioritized over list content."/><Feature icon="⌁" title="Smart filtering" text="Multiple signals classify compilations, rankings, reactions and mashups."/></div></section>
 :<section className="resultsPage"><div className="resultsHeader"><div><div className="eyebrow">SEARCH RESULTS</div><h2>Results for “{query}”</h2></div><Search value={query} setValue={setQuery} submit={submit} mini/></div>
 <div className="filters"><div className="filterScroll">{platforms.map(p=><button key={p} className={active===p?"active":""} onClick={()=>choosePlatform(p)}>{p}</button>)}</div><div className="filterControls"><select value={sort} onChange={e=>chooseSort(e.target.value)}><option value="relevance">Relevance</option><option value="score">Standalone score</option><option value="recent">Newest</option><option value="duration">Shortest</option></select><select value={duration} onChange={e=>chooseDuration(e.target.value)}><option value="any">Any duration</option><option value="under60">Under 1 min</option><option value="under180">Under 3 min</option><option value="1to10">1–10 min</option><option value="over10">Over 10 min</option></select></div></div>
 <div className="resultMeta"><span>{loading?"Searching…":`${results.length} results`}{!loading&&filteredCount?` · ${filteredCount} filtered`:""}{!loading&&duplicateCount?` · ${duplicateCount} duplicates removed`:""}</span><span>{live?"LIVE · YouTube":"DEMO FALLBACK"}</span></div>{error&&<div className="error" role="alert"><strong>Search error</strong><span>{error}</span><button onClick={()=>runSearch(query,limit)}>Retry</button></div>}
 {loading?<div className="loadingGrid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>:results.length?<><div className="resultGrid">{results.map(v=><article className="card" key={v.id}><div className="thumbWrap"><img src={v.thumbnail} alt={`Thumbnail for ${v.title}`} loading="lazy"/><span className="duration">{v.duration}</span><span className="platformBadge">{v.platform}</span></div><div className="cardBody"><h3>{v.title}</h3><p className="desc">{v.description}</p><div className="creator">{v.creator}<span>·</span>{v.age}</div><div className="cardBottom"><span className={v.classification?.type==="standalone"?"standalone":"filtered"}>✓ {v.classification?.type||"unknown"} · {v.score}</span><a href={v.url} target="_blank" rel="noreferrer">Open video ↗</a></div></div></article>)}</div>{results.length>=limit&&<button className="loadMore" disabled={loading} onClick={()=>{const n=Math.min(50,limit+12);setLimit(n);runSearch(query,n)}}>{loading?"Loading…":"Load more"}</button>}</>:<div className="empty"><strong>No standalone results found.</strong><span>Try a broader query, another source, or a different duration.</span></div>}
 <div className="sourcePanel"><div><div className="eyebrow">SOURCE STATUS</div><strong>Connector coverage</strong><p>ClipScout can search up to 8 sources per request. Only sources with legitimate access are marked live.</p><button className="detailsButton" onClick={()=>setShowDetails(v=>!v)} aria-expanded={showDetails}>{showDetails?"Hide details":"Show source details"}</button></div>{showDetails&&<div className="sourceList">{sources.map(s=><span key={s.id} className={s.status}><i aria-hidden="true"/> {s.name} · {s.status}</span>)}</div>}</div>
 </section>}<footer>ClipScout · Cross-platform video discovery · Individual-clip search</footer></main>
}
function Search({value,setValue,submit,mini=false}:{value:string;setValue:(v:string)=>void;submit:(e:FormEvent)=>void;mini?:boolean}){return <form className={mini?"searchBox mini":"searchBox"} onSubmit={submit}><span className="searchIcon">⌕</span><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Try “funny cat moments”..."/><button disabled={!value.trim()}>Search <b>↵</b></button></form>}
function Feature({icon,title,text}:{icon:string;title:string;text:string}){return <div className="feature"><div className="featureIcon">{icon}</div><div><strong>{title}</strong><p>{text}</p></div></div>}
